version: '3'
services:
  ssh_honeypot:
    build:
      context: .
      dockerfile: src/ssh_honeypot/Dockerfile
    container_name: ssh_honeypot
    ports:
      - "2222:2222"
    volumes:
      - ./logs:/app/logs

  http_honeypot:
    build:
      context: .
      dockerfile: src/http_honeypot/Dockerfile
    container_name: http_honeypot
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs





